create table if not exists public.abuse_screening_responses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  page text not null,
  language text not null check (language in ('en', 'es', 'zh', 'pt')),
  score smallint not null check (score between 0 and 10),
  band smallint not null check (band between 0 and 3),
  responses jsonb not null
);

alter table public.abuse_screening_responses enable row level security;

grant insert on public.abuse_screening_responses to anon;
grant usage, select on sequence public.abuse_screening_responses_id_seq to anon;

drop policy if exists "anon can insert abuse screening responses" on public.abuse_screening_responses;
create policy "anon can insert abuse screening responses"
on public.abuse_screening_responses
for insert
to anon
with check (true);
